config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: redirect('users')
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy]
    resources :comments, only: %i[new create destroy]
    resources :likes, only: %i[new create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    can :read, Post # start by defining rules for all users, also not logged ones

    return unless user.present?

    can :manage, Post, author_id: user.id # if the user is logged in can manage it's own posts
    can :manage, Comment, author_id: user.id # logged in users can also create comments

    return unless user.is? :admin

    can :manage, :all # finally we give all remaining permissions only to the admins
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    Post.increment_counter(:comments_counter, post_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    Post.increment_counter(:likes_counter, post_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :author, class_name: 'User'

  after_save :update_posts_counter

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def update_posts_counter
    User.increment_counter(:posts_counter, author_id)
  end

  def latest_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def latest_posts
    Post.where(author_id: id).order(created_at: :desc).limit(3)
  end

  # User::Roles
  # The available roles
  ROLES = %i[admin normal].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new(post_id: @post.id)
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    # new object from params
    @post = Post.find(params[:post_id])
    @comment = Comment.new(post_params)

    # respond_to block
    respond_to do |format|
      format.html do
        if @comment.save
          # success message
          flash[:success] = 'Comment created successfully'
          # redirect to index
          redirect_to user_post_url(id: post_params[:post_id])
        else
          flash.now[:error] = 'Error: Comment could not be created'
          # render new
          render :new, locals: { comment: @comment }
        end
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  private

  def post_params
    post_params = params.require(:comment).permit(:text)
    post_params[:author_id] = current_user.id
    post_params[:post_id] = params.require(:post_id)
    post_params
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def def(_new)
    @like = Like.new
  end

  def create
    # new object from params
    Like.create(author_id: current_user.id, post_id: params[:post_id])
    redirect_to user_post_url(id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id]).order(created_at: :desc).includes(:comments).paginate(
      page: params[:page], per_page: 10
    )
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.where(author_id: params[:user_id]).find(params[:id])
  end

  def new
    @post = Post.new
    @user = current_user
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    # new object from params
    @post = Post.new(post_params)

    # respond_to block
    respond_to do |format|
      format.html do
        if @post.save
          # success message
          flash[:success] = 'Post created successfully'
          # redirect to index
          redirect_to user_posts_url
        else
          flash.now[:error] = 'Error: Post could not be created'
          # render new
          render :new, locals: { post: @post }
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.likes.delete_all
    @post.destroy
    @post.update_posts_counter
    respond_to do |format|
      format.html do
        flash[:success] = 'Post deleted successfully'
        redirect_to user_posts_url
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html { render :edit, locals: { post: @post } }
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html do
        if @post.update(post_params)
          flash[:success] = 'Post updated successfully'
          redirect_to user_posts_url
        else
          flash.now[:error] = 'Error: Post could not be updated'
          render :edit, locals: { post: @post }
        end
      end
    end
  end

  private

  def post_params
    post_params = params.require(:post).permit(:user_id, :title, :text)
    post_params[:author_id] = current_user.id
    post_params
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#create</h1>
  <p>Find me in app/views/comments/create.html.erb</p>
</div>

app/views/comments/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#destroy</h1>
  <p>Find me in app/views/comments/destroy.html.erb</p>
</div>

app/views/comments/new.html.erb
<%= link_to "Back", user_post_path(id: params[:user_id]), class: 'bg-gray-500 rounded-sm text-white self-start p-1 mb-2' %>
<%= form_with model: @comment, url: user_comments_url(post_id: @comment.post_id), class: 'flex flex-col gap-1 items-center mt-24 border-2 p-4' do |f| %>
  <div class="flex gap-3">
    <%= f.label :text, class: 'text-semibold' %>
    <%= f.text_field :text, class: 'border-1 shadow-md h-16 outline-blue-500 p-1' %>
  </div>

  <div class="bg-green-500 mt-4 rounded-sm p-2 text-white">
    <%= f.submit "Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp20</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 max-w-4xl mx-auto p-6 space-y-6">
    <main class="container mx-auto mt-28 px-5 bg-gray-100 max-w-4xl mx-auto p-6 space-y-6">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      

      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Library Info System</title>
      <%= stylesheet_link_tag "style" %>
   </head>

   <body id = "library">
      <div id = "container">
         
         <div id = "header">
            <h1>Library Info System</h1>
            <h3>Library powered by Ruby on Rails</h3>
         </div>

         <div id = "content">
            <%= yield -%>
         </div>

         <div id = "sidebar"></div>
         
      </div>
   </body>
   
</html>

app/views/likes/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Likes#create</h1>
  <p>Find me in app/views/likes/create.html.erb</p>
</div>

app/views/likes/new.html.erb
<%= form_with model: @like, url: user_likes_url do |f| %>
  <div class="bg-green-500 text-white">
    <%= f.submit "Like" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= link_to "Back", user_path(id: params[:user_id]), class: 'bg-gray-500 rounded-sm text-white self-start p-1 mb-2' %>
<div class="flex flex-col w-full">
  <section class="flex items-center justify-between flex-col w-full p-6 bg-white rounded-lg md:flex-row">

    <div class="flex justify-between w-full">

      <div class="w-20 mr-2">
        <img class="w-5 h-4" src=<%= @user.photo %> alt = <%= @user.name %> />
      </div>


      <div class="flex justify-between w-64">
        <h1 class="text-bold text-2xl"><%= @user.name %></h1>
        <p class="number-posts">Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </section>

  <button class="bg-blue-500 text-white p-2 my-1" type="button">
    <%= link_to 'New Post', new_user_post_path %>
  <button>

  <%= will_paginate @posts %>

  <ul class="w-full max-w-4xl mx-auto p-6 space-y-6">
    <% @posts.each do |post| %>
    
      <li class="flex items-center justify-between flex-col w-full p-6 bg-white rounded-lg md:flex-row">
        <div class="flex flex-col justify-between w-full"><h2 class="flex text-bold text-2xl"><%= post.title%></h2>
          <div class="flex justify-between w-48">
            <li>Comments: <%= post.comments_counter %></li>
            <li>Likes: <%= post.likes_counter %></li>
          </div>
        </div>
        <ul class="mt-2">
          <% post.latest_comments.each do |comment| %>
            <li><%= User.find(comment.author_id).name %>: <%= comment.text %></li>
          <% end %>
        </ul>
        <%= link_to "See Post", user_post_path(user_id: params[:user_id], id: post.id), class: 'bg-blue-500 rounded-sm self-center text-white p-1' %>
        <% if can? :manage, post %>
         <li> <%= link_to "Destroy", user_posts_path(post) , data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
          } %> </li>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<%= link_to "Back", user_posts_path, class: 'bg-gray-500 rounded-sm text-white self-start p-1 mb-2' %>
<%= form_with model: @post, url: user_posts_url, class: 'flex flex-col gap-1 items-center mt-24 border-2 p-4' do |f| %>
  <div class="flex gap-3">
    <%= f.label :title, class: 'text-semibold' %>
    <%= f.text_field :title, class: 'border-1 shadow-md p-1 outline-blue-500' %>
  </div>

  <div class="flex gap-3">
    <%= f.label :text, class: 'text-semibold' %>
    <%= f.text_field :text, class: 'border-1 shadow-md h-16 outline-blue-500 p-1' %>
  </div>

  <div class="bg-green-500 mt-4 rounded-sm p-2 text-white">
    <%= f.submit "Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= link_to "Back", user_posts_path, class: 'bg-gray-500 rounded-sm text-white self-start p-1 mb-2' %>
<div class="w-full flex flex-col gap-2 p-4 border-2 p-2">
  <div>
    <p class="text-md font-semibold">Post #<%= @post.id %> by <%= User.find(@post.author_id).name %></p>
    <div class="w-3/6 flex items-center gap-8">
      <p>Comments: <%= @post.comments_counter %></p>
      <p>Likes: <%= @post.likes_counter %></p>
    </div>
  </div>
  <div>
    <h2 class="text-xl font-bold"><%= @post.title %></h2>
    <p><%= @post.text %></p>
  </div>
</div>
<div class="flex gap-2 items-center">
  <%= button_to 'Like', user_likes_url(post_id: @post.id), class: "bg-blue-500 text-white p-2 my-1" %>
  <button class="bg-blue-500 text-white p-2 my-1" type="button">
    <%= link_to 'Comment', new_user_comment_path(post_id: @post.id) %>
  <button>
</div>
<ul class="w-full flex flex-col gap-2 p-4">
<% @post.latest_comments.each do |comment| %>
<li class="border-2 p-2">
  <p><%= User.find(comment.author_id).name %>: <%= comment.text %></p>
  <% if can? :manage, comment %>
    <%= link_to "Delete", user_comment_path(user_id: params[:user_id], id: comment.id),  method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>
<% end %>
</ul>
<% if can? :manage, @post %>
  <%= link_to "Destroy", user_post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
<% end %>

app/views/users/index.html.erb
<ul class="w-full max-w-4xl mx-auto p-6 space-y-6">
  <% @users.each do |user| %>
    <li class="flex items-center justify-between flex-col w-full p-6 bg-white rounded-lg md:flex-row">
      <div class="w-20 mr-2">
        <%= image_tag 'img2.jpg', alt: 'icon'%>
      </div>
        <a href="/users/<%= user.id %>" class="flex w-full">
          <div class="flex justify-between w-full">
          <h2 class="flex text-bold text-2xl"><%= user.name%></h2>
          <p class="flex text-bold text-2xl"><%= user.bio%></p>
          <div>Number of Posts: <%= user.posts_counter%> </div>
          </div>
          <%= link_to "More", user_path(id: user.id), class: 'bg-blue-500 rounded-sm text-white p-1' %>
        </a>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="flex flex-col w-full">

<div class="flex items-center justify-between flex-col w-full p-6 bg-white rounded-lg md:flex-row">

  <div class="w-20 mr-2">
  <%= image_tag 'img2.jpg', alt: 'icon'%>
  </div>


  <div class="flex justify-between w-full">
    <h2 class="flex text-bold text-2xl"><%= @user.name%></h2>
    <div>Number of Posts: <%= @user.posts_counter%> </div>
  </div>

</div>

<div class="flex flex-col w-full bg-white rounded-lg p-6 mt-4">
  <div class="text-bold text-lg"><%=@user.bio %></div>
  <div class="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis obcaecati, eius incidunt suscipit earum esse atque vel, est consequuntur nihil reiciendis culpa iusto repellendus, provident laborum id velit mollitia assumenda.
  Cupiditate autem, eius porro aspernatur enim sequi aut facere maiores odit quisquam debitis dolorum ratione architecto inventore impedit reprehenderit assumenda commodi! Autem libero tempore ea eaque, impedit veniam voluptatibus vitae.</div>
</div>
<ul class="w-full max-w-4xl mx-auto p-6 space-y-6">
  <% @user.latest_posts.each do |post| %>
    <li class="flex items-center justify-between flex-col w-full p-6 bg-white rounded-lg md:flex-row">
      <a href="http://127.0.0.1:3000/users/<%=@user.id%>/posts" class="flex w-full">
        <div class="flex justify-between w-full"><h2 class="flex text-bold text-2xl">Post #<%= post.id %>:<%= post.title%></h2>
        <ul class="flex justify-between w-48">
          <li>Comments: <%= post.comments_counter%></li>
          <li>Likes: <%= post.likes_counter%></li>
        </ul>
        </div>
      </a>
    </li>
  <% end %>
</ul>

<div class="flex justify-center">
<%= link_to "See More", user_posts_path(user_id: @user.id), class: 'bg-blue-500 rounded-sm self-center text-white p-1' %>
</div>


</div>